In [1]:
# import libraries
import pandas as pd
import sqlite3

In [19]:
# Set the display to show more rows and columns
pd.options.display.max_rows = 500
pd.options.display.max_columns = 200

In [6]:
# Assign sqlite database to db variable
db = sqlite3.connect('../data/hop_teaming.sqlite')

In [2]:
nash_refs = pd.read_csv('../data/nashville_referrals_internal.csv')

In [3]:
nash_refs

,index,from_npi,to_npi,patient_count,transaction_count,average_day_wait,std_day_wait,from_zip,from_npi_specialty,to_zip,to_npi_specialty
0,706,1003963976,1003028770,2535,3945,0.000,0.000,37174,Dermatology,37174,Dermatology
1,9754,1033246640,1003863580,58,58,45.603,56.574,37232,Family Medicine,37027,Pathology
2,9755,1033215157,1003863580,124,126,22.833,53.329,38401,Specialist,37027,Pathology
3,9760,1023223898,1003863580,1739,1872,0.169,5.185,37027,Pathology,37027,Pathology
4,9763,1023253549,1003863580,34,53,31.887,50.676,37214,Chiropractor,37027,Pathology
...,...,...,...,...,...,...,...,...,...,...,...
41414,31697042,1255575320,1245485549,914,958,4.653,29.739,37232,Radiology,37204,Radiology
41415,31697044,1235137183,1245485549,198,253,19.470,43.328,37232,Preventive Medicine,37204,Radiology
41416,31697046,1245541846,1245485549,95,111,29.559,52.417,37232,Physical Medicine & Rehabilitation,37204,Radiology
41417,31697048,1255428389,1245485549,191,236,5.004,26.636,37232,Nurse Practitioner,37204,Radiology
41418,31699754,1225389547,1245786482,66,66,22.742,52.898,38401,Physician Assistant,38401,Skilled Nursing Facility

In [25]:
unique_orgs = nash_refs['to_npi'].unique()

In [26]:
unique_orgs

array([1003028770, 1003863580, 1003910688, ..., 1043647142, 1164674818,
       1164761185], dtype=int64)

In [45]:
nash_refs[nash_refs['to_npi'.isin(1972582088,
 1538122569,
 1477588523,
 1669575858,
 1134213648,
 1245393057,
 1063566156,
 1740420538,
 1467687822,
 1104152859,
 1992009500,
 1679835623,
 1710314554,
 1083022818,
 1417404385,
 1558813543,
 1558801332,
 1710478466) == True]]

AttributeError: 'str' object has no attribute 'isin'

In [42]:
find_cent = """
SELECT *
FROM referrals
WHERE to_npi IN (1104152859, 1134213648, 1245393057, 1467687822, 1538122569,
       1558801332, 1669575858, 1679835623, 1992009500)
"""
find_cent = pd.read_sql(find_cent, db)

In [40]:
find_cent.to_npi.unique()

array([1104152859, 1134213648, 1245393057, 1467687822, 1538122569,
       1558801332, 1669575858, 1679835623, 1992009500], dtype=int64)

In [30]:
npi_query = """
    SELECT n.npi, n.provider_organization_name, s.Classification AS specialty

    FROM nppes AS n

    JOIN cbsa AS c
        ON c.ZIP = CAST(n.zip_5 AS INTEGER)
    
    LEFT JOIN specialty AS s
        ON s.npi = n.npi
        
    WHERE n.entity_type_code = 2
    --AND LOWER(s.Classification) LIKE '%hospital%'
    AND LOWER(n.provider_organization_name) LIKE '%centennial%'
"""
org_data = pd.read_sql(npi_query, db)

In [39]:
org_data

,npi,provider_organization_name,specialty
0,1972582088,THE ENDOSCOPY CENTER OF CENTENNIAL LP,Clinic/Center
1,1538122569,CENTENNIAL SURGERY CENTER LP,Clinic/Center
2,1477588523,CENTENNIAL PEDIATRICS PC,Pediatrics
3,1669575858,COLUMBIA MEDICAL GROUP-CENTENNIAL INC,Specialist
4,1134213648,CENTENNIAL SURGICAL ASSOCIATES LLC,Surgery
5,1245393057,CENTENNIAL HEART LLC,Specialist
6,1063566156,HOSPITALISTS AT CENTENNIAL MEDICAL CENTER LLC,Specialist
7,1740420538,CENTENNIAL MEDICAL CENTER,Clinic/Center
8,1467687822,"CENTENNIAL PSYCHIATRIC ASSOCIATES, LLC",Psychiatry & Neurology
9,1104152859,"CENTENNIAL NEUROSCIENCE, LLC",Psychiatry & Neurology
10,1992009500,"CENTENNIAL SURGICAL CLINIC, LLC",Thoracic Surgery (Cardiothoracic Vascular Surg...
11,1679835623,TRISTAR MEDICAL GROUP - CENTENNIAL PRIMARY CAR...,Internal Medicine
12,1710314554,CENTENNIAL,General Acute Care Hospital
13,1083022818,CENTENNIAL HEART,Nurse Practitioner
14,1417404385,"CENTENNIAL HEART, LLC",Internal Medicine
15,1558813543,"CENTENNIAL HEART, LLC",Nurse Practitioner
16,1558801332,"CENTENNIAL HOSPITALISTS, LLC",Internal Medicine
17,1710478466,"CENTENNIAL WOMENS GROUP, LLC",Obstetrics & Gynecology

In [36]:
org_data.npi.to_list()

[1972582088,
 1538122569,
 1477588523,
 1669575858,
 1134213648,
 1245393057,
 1063566156,
 1740420538,
 1467687822,
 1104152859,
 1992009500,
 1679835623,
 1710314554,
 1083022818,
 1417404385,
 1558813543,
 1558801332,
 1710478466]